### ISSUE TITLE
MongoError: pool destroyed

### ISSUE THREAD

**Issue by Sentinas** [sahat/hackathon-starter#1021]
Good day.
When access to the database or the database itself is stopped, an error occurs:
`{ MongoError: pool destroyed
    at Pool.write (../node_modules/mongodb/lib/core/connection/pool.js:860:12)
    at _command (../node_modules/mongodb/lib/core/wireprotocol/command.js:107:10)
    at command (../node_modules/mongodb/lib/core/wireprotocol/command.js:25:5)
    at Object.query (../node_modules/mongodb/lib/core/wireprotocol/query.js:57:3)
    at Server.query (../node_modules/mongodb/lib/core/topologies/server.js:640:16)
    at FindOperation.execute (../node_modules/mongodb/lib/operations/find.js:24:12)
    at topology.selectServer (../node_modules/mongodb/lib/operations/execute_operation.js:163:17)
    at Server.selectServer (../node_modules/mongodb/lib/core/topologies/server.js:828:3)
    at Server.selectServer (../node_modules/mongodb/lib/topologies/topology_base.js:363:32)
    at executeWithServerSelection (../node_modules/mongodb/lib/operations/execute_operation.js:150:12)
    at executeOperation (../node_modules/mongodb/lib/operations/execute_operation.js:81:16)
    at Cursor._initializeCursor (../node_modules/mongodb/lib/core/cursor.js:545:7)
    at Cursor._initializeCursor (../node_modules/mongodb/lib/cursor.js:191:11)
    at nextFunction (../node_modules/mongodb/lib/core/cursor.js:748:10)
    at Cursor._next (../node_modules/mongodb/lib/core/cursor.js:202:5)
    at nextObject (../node_modules/mongodb/lib/operations/common_functions.js:235:10) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
`

Even when access is again, reconnect, or exit by process.exit (); is not happening.
What can be done?

I use a translator.

**Comment by YasharF** [comment]
Are you getting this error on an unmodified project, or is it after adding your custom code to the project?

**Comment by Sentinas** [comment]
I get this error in unmodified code. I call it myself, stopping the mongo service.
The question is that this situation arises constantly when the base is separate. Judging by the function of the connector, the process must be completed. It suits me. Currently the status is unchanged, an internal server error. Even when the database is available.

**Comment by YasharF** [comment]
I can't reproduce the same error.  https://hackathon-starter.walcony.com is running without any errors. 

Which version of NodeJS and MongoDB server are you using?  Are you using a standalone MongoDB instance or is it a hosted instance such as MongoDB Atlas?  Could it be that you have a corrupt database?

**Comment by Sentinas** [comment]
I'm using the MongoDB Atlas pool.
And periodically such an error occurs. There is no reconnect to the base before rebooting the app.

**Comment by YasharF** [comment]
I am not sure how far the server and the MongoDB hosts are located from each other or what type of connection is in between them, but if I have to guess, I think you might be dealing with the problem at https://github.com/Automattic/mongoose/issues/6759#issuecomment-414152155 .  In other words, it is taking too long for the NodeJS instance to talk to the MongoDB instance and the database gives up and closes the connection.  Once it is closed, then you get the error.

**Comment by Sentinas** [comment]
Thanks. This seems like what it takes. Setting the Driver Reconnect Interval.
