### ISSUE TITLE
I am getting csrf error

### ISSUE THREAD

**Issue by davidnalbandian143** [sahat/hackathon-starter#1056]
after uploading form with file upload , i am redirecting the to the same place through post router.
I am getting csrf missing but data has been sending to data base 

**Error in console:**

Error: CSRF token missing
    at checkCsrf (C:\Users\RudraSimha\desktop\hackthon\node_modules\lusca\lib\csrf.js:151:18)
    **at C:\Users\RudraSimha\desktop\hackthon\app.js:105:17**
    at Layer.handle [as handle_request] (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\RudraSimha\desktop\hackthon\node_modules\express-flash\lib\express-flash.js:31:7
    at C:\Users\RudraSimha\desktop\hackthon\node_modules\connect-flash\lib\flash.js:21:5
    at C:\Users\RudraSimha\desktop\hackthon\node_modules\express-flash\lib\express-flash.js:22:5
    at Layer.handle [as handle_request] (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:275:10)
    at SessionStrategy.strategy.pass (C:\Users\RudraSimha\desktop\hackthon\node_modules\passport\lib\middleware\authenticate.js:343:9)
    at SessionStrategy.authenticate (C:\Users\RudraSimha\desktop\hackthon\node_modules\passport\lib\strategies\session.js:75:10)
    at attempt (C:\Users\RudraSimha\desktop\hackthon\node_modules\passport\lib\middleware\authenticate.js:366:16)
    at authenticate (C:\Users\RudraSimha\desktop\hackthon\node_modules\passport\lib\middleware\authenticate.js:367:7)
    at Layer.handle [as handle_request] (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:275:10)
    at initialize (C:\Users\RudraSimha\desktop\hackthon\node_modules\passport\lib\middleware\initialize.js:53:5)
    at Layer.handle [as handle_request] (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\RudraSimha\desktop\hackthon\node_modules\express\lib\router\index.js:284:7
POST /create-photo-campaign 500 245.256 ms - 12

{
  _id: 5ea65dd343381a4468a33e73,
  Campname: 'dfbd',
  Title: 'rsbsr',
  Email: 'eventtitans123@gmail.com',
  Start: 2014-05-13T18:30:00.000Z,
  End: 2014-05-21T18:30:00.000Z,
  Time: '09:30',
  Description: '<p>fbdfbdgbgbdgn</p>',
  Campcolor: '#5367ce',
  Banner: 'uploads/',

**at the 105 line my code is :**

app.use((req, res, next) => {
  if (req.path === '/api/upload') {
    // Multer multipart/form-data handling needs to occur before the Lusca CSRF check.
    next();
  } else {
    lusca.csrf()(req, res, next);
  }
});

I am using express-file upload instead of multer

**Comment by YasharF** [comment]
> I am using express-file upload instead of multer
You need to find out how to handle the csrf token when using the express-file upload

**Comment by davidnalbandian143** [comment]
Solved , Thank you
