### ISSUE TITLE
Warning flash message 'errorrs' undefined with pug-cli

### ISSUE THREAD

**Issue by mohammadanton** [sahat/hackathon-starter#1065]
I use emacs pug-mode that automatically compiled .pug files
Every .pug files that extends ..layout always show error like this
layout.pug show the same error because it contain 'include partials/flash'

But if I open localhost:8080, Flash message works fine,
show this error only happen in my text editor

I think this bug happens because of
object "message" in partials/flash.pug line 1 is declared in the controller

Is there a way to ignore this error?

```
-*- mode: compilation; default-directory: "~/Projects/practice/sahat-demo/views/" -*-
Compilation started at Mon Jul  6 10:05:13

pug /home/me/Projects/practice/sahat-demo/views/layout.pug

/home/me/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-runtime/index.js:253
  throw err;
  ^

TypeError: /home/me/Projects/practice/sahat-demo/views/partials/flash.pug:1
  > 1| if messages.errors
    2|   .alert.alert-danger.fade.show
    3|     button.close(type='button', data-dismiss='alert')
    4|       i.far.fa-times-circle

Cannot read property 'errors' of undefined
    at eval (eval at wrap (/home/me/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:134:14)
    at template (eval at wrap (/home/me/.npm-packages/lib/node_modules/pug-cli/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:295:119)
    at renderFile (/home/me/.npm-packages/lib/node_modules/pug-cli/index.js:285:40)
    at /home/me/.npm-packages/lib/node_modules/pug-cli/index.js:149:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/me/.npm-packages/lib/node_modules/pug-cli/index.js:148:9)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14) {
  path: '/home/me/Projects/practice/sahat-demo/views/partials/flash.pug'
}

Compilation exited abnormally with code 1 at Mon Jul  6 10:05:13

```

**Comment by YasharF** [comment]
This is probably a better question for emacs pug-mode.

**Comment by mohammadanton** [comment]
I ignore the warning it by adding ternary conditional for each flash type

```
if messages ? messages.errors : ''
if messages ? messages.info : ''
if messages ? messages.success : ''

```
