### ISSUE TITLE
Bug: Handling Expired Tokens

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#1104]
The app is supposed to identify if a token has expired and take the proper action to refresh it or reauthenticate the user.  The current logic seems to be broken as this is not quite happening, and the app either crashes or shows a server error and the user will have to unlink their API credentials in /account and retry to get the app to reauthenticate with the oAuth provider.

I have seen this issue in the Google Sheets API integration as well as the Quickbooks API integration.

The error in the Quickbooks case is:
```
2020-10-13T16:03:35.048560+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/api/quickbooks" host=hackathon-starter.walcony.com request_id=d70xxxxxxxxxxxxxxxxxfdc fwd="26xxxxxxxxxxxxxxxxxxxxxx33" dyno=web.1 connect=1ms service=307ms status=503 bytes=0 protocol=http
2020-10-13T16:03:35.010803+00:00 app[web.1]: events.js:291
2020-10-13T16:03:35.010812+00:00 app[web.1]: throw er; // Unhandled 'error' event
2020-10-13T16:03:35.010812+00:00 app[web.1]: ^
2020-10-13T16:03:35.010813+00:00 app[web.1]:
2020-10-13T16:03:35.010813+00:00 app[web.1]: TypeError: Cannot read property 'expires_in' of undefined
2020-10-13T16:03:35.010814+00:00 app[web.1]: at /app/config/passport.js:749:30
2020-10-13T16:03:35.010814+00:00 app[web.1]: at CoreMongooseArray.some (<anonymous>)
2020-10-13T16:03:35.010815+00:00 app[web.1]: at /app/config/passport.js:746:27
2020-10-13T16:03:35.010815+00:00 app[web.1]: at /app/node_modules/mongoose/lib/model.js:4842:16
2020-10-13T16:03:35.010816+00:00 app[web.1]: at /app/node_modules/mongoose/lib/model.js:4842:16
2020-10-13T16:03:35.010816+00:00 app[web.1]: at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
2020-10-13T16:03:35.010817+00:00 app[web.1]: at /app/node_modules/mongoose/lib/model.js:4865:21
2020-10-13T16:03:35.010817+00:00 app[web.1]: at /app/node_modules/mongoose/lib/query.js:4419:11
2020-10-13T16:03:35.010817+00:00 app[web.1]: at /app/node_modules/kareem/index.js:135:16
2020-10-13T16:03:35.010818+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:75:11)
2020-10-13T16:03:35.010818+00:00 app[web.1]: at runNextTicks (internal/process/task_queues.js:62:3)
2020-10-13T16:03:35.010819+00:00 app[web.1]: at processImmediate (internal/timers.js:434:9)
2020-10-13T16:03:35.010819+00:00 app[web.1]: Emitted 'error' event on Function instance at:
2020-10-13T16:03:35.010819+00:00 app[web.1]: at /app/node_modules/mongoose/lib/model.js:4844:13
2020-10-13T16:03:35.010820+00:00 app[web.1]: at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
2020-10-13T16:03:35.010820+00:00 app[web.1]: [... lines matching original stack trace ...]
2020-10-13T16:03:35.010820+00:00 app[web.1]: at processImmediate (internal/timers.js:434:9)
2020-10-13T16:03:35.055553+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-10-13T16:03:35.055996+00:00 app[web.1]: npm ERR! errno 1
2020-10-13T16:03:35.061492+00:00 app[web.1]: npm ERR! hackathon-starter@6.0.1 start: `node app.js`
2020-10-13T16:03:35.061648+00:00 app[web.1]: npm ERR! Exit status 1
2020-10-13T16:03:35.061822+00:00 app[web.1]: npm ERR!
2020-10-13T16:03:35.061985+00:00 app[web.1]: npm ERR! Failed at the hackathon-starter@6.0.1 start script.
2020-10-13T16:03:35.062143+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-10-13T16:03:35.071223+00:00 app[web.1]:
2020-10-13T16:03:35.071510+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-10-13T16:03:35.071620+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-10-13T16_03_35_062Z-debug.log
2020-10-13T16:03:35.259213+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by HarshAulakh** [comment]
Hey @YasharF , I would like to work on this.

**Comment by dhairyagada** [comment]
How can I reproduce this issue?

**Comment by YasharF** [comment]
It happens weeks after a successful login.

**Comment by YasharF** [comment]
Maybe Nock could be used to implement a unit test and to expose the issue.  We can potentially have that test coverage improvement as a separate PR.

**Comment by YasharF** [comment]
For some ideas, Google has this typescript example that uses nock to test API Oauth2 related functions: https://github.com/googleapis/google-api-nodejs-client/blob/master/test/test.auth.ts

**Comment by zilehuda** [comment]
@YasharF I am working on this.

**Comment by dewanshrawat15** [comment]
@YasharF I think a simple check to see if ```params``` is undefined can help fix this issue.
