### ISSUE TITLE
got 500 Error: Error setting TTL index on collection : sessions

### ISSUE THREAD

**Issue by pockry** [sahat/hackathon-starter#191]
This happened when I restart computer and first start mongodb and my node app and load the web page. and when I refresh the page the error gone.
 the other error infomation:

```
500 Error: Error setting TTL index on collection : sessions
   at C:\git\xinfans\node_modules\connect-mongo\lib\connect-mongo.js:161:23
   at C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1404:28
   at C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1542:30
   at C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:159:22
   at commandHandler (C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:678:48)
   at C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1806:9
   at __executeQueryCommand (C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1636:44)
   at Db._executeQueryCommand (C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1805:7)
   at Cursor.nextObject (C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:729:13)
   at Cursor.toArray (C:\git\xinfans\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:158:10)
```

I googled it and find this stackoverflow which seems can fix it.
http://stackoverflow.com/questions/22698661/mongodb-error-setting-ttl-index-on-collection-sessions

The connect-mongo module in app.js seems needs a callback.

Hope this will help :)

**Comment by nagendrayadav88** [comment]
Hello, 
Please help, 
How to resolve It,
Error: Error getting collection: sessions
    at C:\Users\DEV_Nagu\Desktop\Faelo-food-order-app-MEAN.js--master\node_modules\connect-mongo\lib\connect-mongo.js:160:19
