### ISSUE TITLE
!= css('main') not loading

### ISSUE THREAD

**Issue by ricksturgeon** [sahat/hackathon-starter#222]
After loading when I run node app.js I get this error:

500 TypeError: /Users/ricksturgeon/express_apps/arranger_test/myproject/views/layout.jade:9

       7|     meta(name='csrf-token', content=_csrf)
       8|     title #{title} - Hackathon Starter
     > 9|     != css('main')
       10|   body
       11|     include partials/navbar
       12| 
Argument must be a string
   at new ProcessedAsset (/Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/assets/processed.js:149:24)
   at /Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:541:12
   at circular_call_protection (/Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:514:12)
   at Index.Base.buildAsset (/Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:540:10)
   at /Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:141:26
   at Index.module.exports.cacheAsset (/Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/helpers/caching.js:52:12)
   at Index.buildAsset (/Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:140:33)
   at Index.Base.findAsset (/Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:350:15)
   at Index.findAsset (/Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:114:22)
   at new BundledAsset (/Users/ricksturgeon/express_apps/arranger_test/myproject/node_modules/connect-assets/node_modules/mincer/lib/mincer/assets/bundled.js:53:37)

When I change to: <link href="css/main.scss" type="text/css" rel="stylesheet"> the scss file loads but the app does not properly layout.

Ideas??

**Comment by sahat** [comment]
There is a similar issue on connect assets but no one has replied to it yet: https://github.com/adunkman/connect-assets/issues/289

I don't know why you are getting that error. Double check that you have installed `node-sass` package without any errors. Sometimes you run `npm install` and may miss build errors in the middle of the install process. Make sure you have gcc / c++ compiler installed on your computer. Try installing Ruby + Sass gem. Lots of things to try, eventually one of those will fix the problem.

**Comment by ricksturgeon** [comment]
I did all the above and it still did not work. I re-installed several times on my mac. The I installed it with "sudo npm install"  from the beginning in a new directory and all worked perfectly!  Thanks for the support and the great script.

Rick

**Comment by chinmayrane** [comment]
It didn't help. Am on Windows though. Anything that can be referenced? I guess it's a mincer problem. :-1:

**Comment by chinmayrane** [comment]
Ohkay. This is wierd. I cloned this project. 
Did an npm install.
Copied the node-sass module created in the node-modules section.

Ans Viola, it runs like a charm.
This is surely version dependency .Will figure it out soon! :)

**Comment by geggleto** [comment]
I had to lower the node-sass version to 1.2.3

**Comment by WhayP** [comment]
True, so it was @^1.2.3 

This might messup later! :+1:

**Comment by sahat** [comment]
node-sass 1.2.3 is the latest stable version. The new 2.0.0 beta is currently not compatible with `mincer` unfortunately.

**Comment by bzz** [comment]
This issues is resolved with stable node-sass@2.0.0 AND adunkman/connect-assets#289 fixed (by manually installing latest nodeca/mincer in ```./node_modules/connect-assets``` with nodeca/mincer#186 merged)

**Comment by WhayP** [comment]
Thanks and Sahat Sir reverted back to less. :+1:
