### ISSUE TITLE
first start ever immediate issue

### ISSUE THREAD

**Issue by scamianbas** [sahat/hackathon-starter#256]
Hi,
after having run the following commands as stated in readme:
$ git clone --depth=1 https://github.com/sahat/hackathon-starter.git myHSproject
$ cd myHSproject
$ git remote rm origin
$ npm install
$ nodemon app.js

I'm getting the following error... Any ideas ?
Thanks.

/home/ubuntu/myHSproject/node_modules/lob/node_modules/bluebird/js/main/async.js:75
        Object.defineProperty(EventsModule, "usingDomains", {
               ^
TypeError: Cannot redefine property: usingDomains
    at Function.defineProperty (native)
    at Object.<anonymous> (/home/ubuntu/myHSproject/node_modules/lob/node_modules/bluebird/js/main/async.js:75:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/home/ubuntu/myHSproject/node_modules/lob/node_modules/bluebird/js/main/promise.js:13:13)
    at Object.<anonymous> (/home/ubuntu/myHSproject/node_modules/lob/node_modules/bluebird/js/main/bluebird.js:9:39)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
2 Apr 10:21:51 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by odino** [comment]
I think there is an error in request promise, check if they just released something :)

**Comment by sahat** [comment]
This should be fixed in the latest release of Bluebird that LOB API uses. https://github.com/petkaantonov/bluebird/releases
