### ISSUE TITLE
Forgot password stack trace

### ISSUE THREAD

**Issue by mccauleycolm** [sahat/hackathon-starter#261]
The following stack trace is appearing when I click on Forgot Password with a legit username:
```js
Connect
500 Error: Invalid login
   at SMTPConnection._formatError (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:388:15)
   at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:841:30)
   at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:243:22)
   at SMTPConnection._processResponse (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:507:16)
   at SMTPConnection._onData (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:357:10)
   at CleartextStream.emit (events.js:95:17)
   at CleartextStream.<anonymous> (_stream_readable.js:765:14)
   at CleartextStream.emit (events.js:92:17)
   at emitReadable_ (_stream_readable.js:427:10)
   at _stream_readable.js:420:7
```

**Comment by sahat** [comment]
Thanks, I will take a look at it. Seems like a nodemailer issue for sending out emails.

**Comment by sahat** [comment]
My Sendgrid account username and password that you see in secrets.js has been suspended. Which doesn't surprise me at all.

You should create your own SendGrid account or Mailgun or whatever service you wish to use and use that for sending emails, e.g.:
```
var transporter = nodemailer.createTransport({
    service: 'Gmail',
    auth: {
        user: 'gmail.user@gmail.com',
        pass: 'userpass'
    }
});
```

**Comment by CZ-git** [comment]
Connect
500 Error: Invalid login
   at SMTPConnection._formatError (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:387:15)
   at SMTPConnection._actionAUTHComplete (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:838:30)
   at SMTPConnection.<anonymous> (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:242:22)
   at SMTPConnection._processResponse (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:506:16)
   at SMTPConnection._onData (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:356:10)
   at CleartextStream.emit (events.js:95:17)
   at CleartextStream.<anonymous> (_stream_readable.js:764:14)
   at CleartextStream.emit (events.js:92:17)
   at emitReadable_ (_stream_readable.js:426:10)
   at _stream_readable.js:419:7
   at process._tickCallback (node.js:419:13)

Still error occured. What's wrong?

**Comment by CZ-git** [comment]
I've changed the service username and password as mine.
Could you please teach me?
