### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by vosahloj** [sahat/hackathon-starter#278]
I have followed the Getting Started section, after starting via node app.js, I get the following error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.app.listen (/Users/vosahloj/ws/hspokus/node_modules/express/lib/application.js:595:24)
    at Object.<anonymous> (/Users/vosahloj/ws/hspokus/app.js:199:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by sahat** [comment]
Are you running another Node.js process on port 3000?

**Comment by vosahloj** [comment]
Oh my... I can't even read the log :-(

Yes, you are right. Another app has been running on the same port. My bad!
