### ISSUE TITLE
500 Error: Invalid login

### ISSUE THREAD

**Issue by CZ-git** [sahat/hackathon-starter#279]
I am Honzik Kasperak.
Now I am implementing the forgest password feature, so I am using your sample. But the error occur like that. Could you please let me know how to fix this issue?

Connect
500 Error: Invalid login
   at SMTPConnection._formatError (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:387:15)
   at SMTPConnection._actionAUTHComplete (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:838:30)
   at SMTPConnection.<anonymous> (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:242:22)
   at SMTPConnection._processResponse (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:506:16)
   at SMTPConnection._onData (D:\Bid_Task\2015-04-09(Dan)\authentication-module\hackathon-starter-master\hackathon-starter-master\node_modules\nodemailer\node_modules\nodemailer-smtp-transport\node_modules\smtp-connection\src\smtp-connection.js:356:10)
   at CleartextStream.emit (events.js:95:17)
   at CleartextStream.<anonymous> (_stream_readable.js:764:14)
   at CleartextStream.emit (events.js:92:17)
   at emitReadable_ (_stream_readable.js:426:10)
   at _stream_readable.js:419:7
   at process._tickCallback (node.js:419:13)

This is error message.
Please teach me.
Thanks.

**Comment by CZ-git** [comment]
Hi.

I have to fix this issue quickly.
Please help me.

Regards.

**Comment by sahat** [comment]
This project uses SendGrid for sending out emails. The username and password I included in hackathon starter are long since they have been blocked by SendGrid. You weren't supposed to use them anyway, it was there to help you get started.

```js
var transporter = nodemailer.createTransport({
        service: 'SendGrid',
        auth: {
          user: secrets.sendgrid.user,
          pass: secrets.sendgrid.password
        }
      });
```

In `users.js` controller change service to Gmail, Sendgrid, Mailgun, iCloud or whatever it is you want to use and then use your username and password with that service.

**Comment by CZ-git** [comment]
Hi.

I used the sendgrid services with my username and password.
But it's not working.
