### ISSUE TITLE
Error on multer

### ISSUE THREAD

**Issue by OlivierCuyp** [sahat/hackathon-starter#302]
Hi, here is the error I get right after `npm install`, `node app.js`.
```
/Users/olivier/Playground/hackathon/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
          ^
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/Users/olivier/Playground/hackathon/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/Users/olivier/Playground/hackathon/app.js:66:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by sahat** [comment]
Multer API has been updated, it's no longer a middleware, I just removed it altogether to avoid having variables that are defined but never used. If I do add File Upload example in the future, I can add multer  then.
