### ISSUE TITLE
Sign In with LinkedIn 

### ISSUE THREAD

**Issue by davykiala** [sahat/hackathon-starter#338]
Sign In With LinkedIn seems do not work ! 
I went to http://hackathonstarter.herokuapp.com/login and click on "Sign In With LinkedIn" button but i get the following error : 

500 AuthorizationError: Your application has not been authorized for the scope "r_fullprofile"
   at Strategy.OAuth2Strategy.authenticate (/app/node_modules/passport-linkedin-oauth2/node_modules/passport-oauth2/lib/strategy.js:126:25)
   at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:341:16)
   at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:342:7)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/app/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at /app/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
   at next (/app/node_modules/express/lib/router/index.js:271:10)
   at SendStream.error (/app/node_modules/express/node_modules/serve-static/index.js:120:7)
   at SendStream.emit (events.js:107:17)
   at SendStream.error (/app/node_modules/express/node_modules/send/index.js:245:17)
   at SendStream.onStatError (/app/node_modules/express/node_modules/send/index.js:356:12)
   at next (/app/node_modules/express/node_modules/send/index.js:630:16)
   at onstat (/app/node_modules/express/node_modules/send/index.js:619:14)
   at FSReqWrap.oncomplete (fs.js:95:15)

I

**Comment by Shipow** [comment]
unless you're in the partnership program of linkedin you won't be able anymore to access to this permissions.
Here are the 'public' permissions available
![image](https://cloud.githubusercontent.com/assets/976175/11318189/b57326b0-9047-11e5-994c-3fc1cf4a1f87.png)

**Comment by davykiala** [comment]
Ok thanks

**Comment by sahat** [comment]
I have updated the scope and linkedin example.
