### ISSUE TITLE
Why the machine make the mistake, configure the environment right, please help

### ISSUE THREAD

**Issue by warren2015tail** [sahat/hackathon-starter#387]
root@iZ25nvtqoljZ myproject]# node app.js 
/root/myproject/node_modules/node-sass-middleware/node_modules/node-sass/lib/extensions.js:150
    throw new Error([
    ^

Error: The `libsass` binding was not found in /root/myproject/node_modules/node-sass-middleware/node_modules/node-sass/vendor/linux-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/root/myproject/node_modules/node-sass-middleware/node_modules/node-sass/lib/extensions.js:150:11)
    at Object.<anonymous> (/root/myproject/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/myproject/node_modules/node-sass-middleware/middleware.js:3:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/myproject/app.js:20:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
[root@iZ25nvtqoljZ myproject]# ls

**Comment by sahat** [comment]
Please google the problem first: [search results](https://www.google.com/search?q=Error%3A+The+libsass+binding+was+not+found+in+%2Froot%2Fmyproject%2Fnode_modules%2Fnode-sass-middleware%2Fnode_modules%2Fnode-sass%2Fvendor%2Flinux-x64-46%2Fbinding.node&oq=Error%3A+The+libsass+binding+was+not+found+in+%2Froot%2Fmyproject%2Fnode_modules%2Fnode-sass-middleware%2Fnode_modules%2Fnode-sass%2Fvendor%2Flinux-x64-46%2Fbinding.node&aqs=chrome..69i57j69i58.449j0j7&sourceid=chrome&es_sm=122&ie=UTF-8#q=Error:+The+libsass+binding+was+not+found+in+node-sass%2Fvendor%2Flinux-x64-46%2Fbinding.node)

The issue is not with the hackathon-starter but with your node.js environment and/or missing build tools necessary to compile libsass library.
