### ISSUE TITLE
Trying to convert this to handlebars

### ISSUE THREAD

**Issue by joshterrill** [sahat/hackathon-starter#392]
Hello

I'm trying to convert these jade files to handlebars files. I went to test the user sign up and I'm getting this error:

```
Connect
403 Error: CSRF token missing
   at checkCsrf (C:\Users\Josh\Projects\hackathon-starter\node_modules\lusca\lib\csrf.js:89:18)
   at C:\Users\Josh\Projects\hackathon-starter\app.js:94:17
   at Layer.handle [as handle_request] (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:312:13)
   at C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:271:10)
   at C:\Users\Josh\Projects\hackathon-starter\node_modules\express-flash\lib\express-flash.js:31:7
   at C:\Users\Josh\Projects\hackathon-starter\node_modules\connect-flash\lib\flash.js:21:5
   at C:\Users\Josh\Projects\hackathon-starter\node_modules\express-flash\lib\express-flash.js:22:5
   at Layer.handle [as handle_request] (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:312:13)
   at C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:271:10)
   at SessionStrategy.strategy.pass (C:\Users\Josh\Projects\hackathon-starter\node_modules\passport\lib\middleware\authenticate.js:325:9)
   at SessionStrategy.authenticate (C:\Users\Josh\Projects\hackathon-starter\node_modules\passport\lib\strategies\session.js:71:10)
   at attempt (C:\Users\Josh\Projects\hackathon-starter\node_modules\passport\lib\middleware\authenticate.js:348:16)
   at authenticate (C:\Users\Josh\Projects\hackathon-starter\node_modules\passport\lib\middleware\authenticate.js:349:7)
   at Layer.handle [as handle_request] (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:312:13)
   at C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:271:10)
   at initialize (C:\Users\Josh\Projects\hackathon-starter\node_modules\passport\lib\middleware\initialize.js:53:5)
   at Layer.handle [as handle_request] (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:312:13)
   at C:\Users\Josh\Projects\hackathon-starter\node_modules\express\lib\router\index.js:280:7
```

Do you know what could be causing this?

My mongodb is connecting to a mongolab URL, when I looked in the mongolab database, I see two collections, sessions (1), and users (0). The one document in sessions reads:

```
{
    "_id": "S3Yy0dqlnAk-weiW8WeEoWgBYEtgQwDQ",
    "session": "{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"_csrfSecret\":\"m2Cl6l6t4m37rw==\",\"flash\":{},\"returnTo\":\"/api\"}",
    "expires": {
        "$date": "2016-03-16T05:51:47.775Z"
    }
}
```

One of the files that I haven't turned into handlebars yet is the flash file because there are some references to variables, so I skipped over it for now. Not sure if that's related to what's going on or not.

If it makes it easier to look at, I've committed my changes to my local fork of the repo here: https://github.com/joshterrill/hackathon-starter

**Comment by sahat** [comment]
You have created a CSRF hidden input form field, but it does not contain any value. That's the issue.

```html
  <input type="hidden" name="_csrf"/>
```

**Comment by joshterrill** [comment]
I saw that, but I couldn't find where that value was coming from. The only csrf mention I saw was in `app.js` at https://github.com/sahat/hackathon-starter/blob/master/app.js#L92 How does the value get generated?

**Comment by joshterrill** [comment]
I added this:

```
exports.getSignup = function (req, res) {
  if (req.user) {
    return res.redirect('/');
  }
  res.render('account/signup', {
    title: 'Create Account',
    csrf: req.csrfToken()
  });
};
```

I was able to sign up, but it didn't log me in. It did create a record in the user collection in the database. And now when I click any links, it redirects me to /.... What did I mess up?

**Comment by joshterrill** [comment]
I looked in the jade template and it seems the `_csrf` variable is available globally, so I added 
` <input type="hidden" name="_csrf" value="{{_csrf}}"/>`
To the signup and login page. Same thing still happens. Clicking links always redirects me to /

**Comment by sahat** [comment]
A good way to check would be to print that value as a h1 heading. That way you will know if CSRF value is even present in the handlebars template. It should be available the same way it is available in Jade templates.

**Comment by sahat** [comment]
Ah ok. I didn't see your update.
