### ISSUE TITLE
"TypeError: Cannot set property 'warn_function' of undefined" on GET /

### ISSUE THREAD

**Issue by tillda** [sahat/hackathon-starter#419]
When opening / I get the following stacktrace. My Node is 5.9.0 and the checked-out commit is 0db876e7ef663cef664885ad21a08fc4c7e74751. Both `npm install` and `node app.js` go fine.
 
```
TypeError: Cannot set property 'warn_function' of undefined
    at Object.<anonymous> (/Users/michal/Tryouts/hackatone-starter/node_modules/uglify-js/tools/node.js:42:33)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/michal/Tryouts/hackatone-starter/node_modules/jade/lib/filters.js:5:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/michal/Tryouts/hackatone-starter/node_modules/jade/lib/parser.js:6:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/michal/Tryouts/hackatone-starter/node_modules/jade/lib/index.js:13:14)
```

**Comment by sahat** [comment]
I am not able to reproduce this issue with Node.js 5.9, even after removing node_modules and running npm install again.
