### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by panayi** [sahat/hackathon-starter#463]
Deployed to Heroku (without any changes) and getting this error:

```
> heroku logs
2016-05-17T14:05:39.099949+00:00 app[web.1]: > node app.js
2016-05-17T14:05:39.099949+00:00 app[web.1]:
2016-05-17T14:05:40.412849+00:00 app[web.1]:     for (let i = 0; i < links.length; i++) {
2016-05-17T14:05:40.412855+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2016-05-17T14:05:40.412855+00:00 app[web.1]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
2016-05-17T14:05:40.412875+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-05-17T14:05:40.412853+00:00 app[web.1]:          ^^^
2016-05-17T14:05:40.412877+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-05-17T14:05:40.412874+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-05-17T14:05:40.412876+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-05-17T14:05:40.412878+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-05-17T14:05:40.412854+00:00 app[web.1]:
2016-05-17T14:05:40.412841+00:00 app[web.1]: /app/controllers/api.js:629
2016-05-17T14:05:40.412876+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-05-17T14:05:40.412879+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-05-17T14:05:40.412878+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:32:23)
2016-05-17T14:05:40.412880+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-05-17T14:05:40.412879+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-05-17T14:05:40.412881+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-05-17T14:05:40.412882+00:00 app[web.1]:     at startup (node.js:148:18)
2016-05-17T14:05:40.412883+00:00 app[web.1]:     at node.js:405:3
2016-05-17T14:05:40.469964+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-05-17T14:05:40.412881+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-05-17T14:05:40.472816+00:00 app[web.1]: npm ERR! hackathon-starter@3.5.0 start: `node app.js`
2016-05-17T14:05:40.472567+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-05-17T14:05:40.470595+00:00 app[web.1]: npm ERR! npm  v3.8.6
```

**Comment by sahat** [comment]
Try adding `engine` option to package.json:

```js
"engines": {
  "node": "6.1.0"
}
```

Let me know if this fixes the issue. My guess is that it falls back to LTS 4.x version by default when no engine is specified. But I could be wrong.

**Comment by panayi** [comment]
That fixed it thanks 👍 

There was another issue though, the ENV variable name on Heroku is different than the one specified in `app.js`. The following fixed it for me:

![image](https://cloud.githubusercontent.com/assets/707005/15334849/886d0844-1c78-11e6-981a-23d5ef9ca982.png)

**Comment by sahat** [comment]
Thanks, both issues have been fixed in the latest 2 commits.

**Comment by eveyrat** [comment]
Hi guys,
Same problem here and i just pulled the last commits.

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

Thanks for your help !

**Comment by talantbekov123** [comment]
It worked! Thank you!

**Comment by daniavram** [comment]
Thank you. so much :) 👍

**Comment by anthonydelgado** [comment]
Awesome! Just worked! THANKS!
