### ISSUE TITLE
Error when running 'node app.js'

### ISSUE THREAD

**Issue by ankerbachryhl** [sahat/hackathon-starter#495]
When I am running node app.js after I have installed all the dependencies, I am getting this error:

`C:\Users\Anker\documents\code\basic-auth\controllers\api.js:629
    for (let i = 0; i < links.length; i++) {
         ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Anker\documents\code\basic-auth\app.js:32:23
)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

`

Do you guys have any clue why? I have tried on both mac and windows and I am getting the same error both places :(

**Comment by ankerbachryhl** [comment]
Got it working! Awesome repo Thank YOU! 👍
