### ISSUE TITLE
Forgot password issue.

### ISSUE THREAD

**Issue by gobindaakhuli** [sahat/hackathon-starter#514]
Sign in by a google account with a unregistered hackathonstarter email id it will be log in correctly. But after that if put this email id in forgot password box and press reset password then it shows an error.

Connect
500 Error: Invalid login: 535 Authentication failed: account disabled

       at SMTPConnection._formatError (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:484:15)
       at SMTPConnection._actionAUTHComplete (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:1069:30)
       at SMTPConnection.<anonymous> (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:298:22)
       at SMTPConnection._processResponse (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:622:16)
       at SMTPConnection._onData (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:449:10)
       at emitOne (events.js:96:13)
       at TLSSocket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:172:18)
       at TLSSocket.Readable.push (_stream_readable.js:130:10)
       at TLSWrap.onread (net.js:542:20)

![screenshot from 2016-07-08 16-37-12](https://cloud.githubusercontent.com/assets/7501472/16685951/3e103abe-452c-11e6-9db0-bd1b801576b3.png)

**Comment by sahat** [comment]
You will need to supply your own Mailgun or Sendgrid credentials for sending emails.
