### ISSUE TITLE
Forgotten Password results in HTTP 500 error

### ISSUE THREAD

**Issue by budda** [sahat/hackathon-starter#539]
I created an account by signing in using Twitter.
I then unlinked my Twitter account from the profile and continued to update my profile by setting a gender. The email address was left as the default generated "username@twitter.com" one
I then logged out.

I attempted to a do a forgotten password request on username@twitter.com and got a 500 error possibly because the code wasn't expecting the 535 error from the Twitter API?

```
Connect
500 Error: Invalid login: 535 Authentication failed: account disabled
   at SMTPConnection._formatError (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:484:15)
   at SMTPConnection._actionAUTHComplete (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:1069:30)
   at SMTPConnection.<anonymous> (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:298:22)
   at SMTPConnection._processResponse (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:622:16)
   at SMTPConnection._onData (/var/lib/openshift/577472bf2d52711b0f0000f5/app-root/runtime/repo/node_modules/smtp-connection/lib/smtp-connection.js:449:10)
   at emitOne (events.js:96:13)
   at TLSSocket.emit (events.js:188:7)
   at readableAddChunk (_stream_readable.js:172:18)
   at TLSSocket.Readable.push (_stream_readable.js:130:10)
   at TLSWrap.onread (net.js:542:20)
```

Would be nice to cleanly handle the situation with an on page message or for security should it say something along the lines of "If your account was found login details will be emailed." message.

**Comment by sahat** [comment]
@budda It's an unhandled error from Nodemailer. Basically, it is trying to send you an email but my my current Mailgun credentials are suspended, that's why you are seeing that error. If you create and use your own API keys (as you should), the error message will go away.

**Comment by budda** [comment]
Ah, i was testing it on your demo domain before doing anything local.
