### ISSUE TITLE
Mongoose timeout

### ISSUE THREAD

**Issue by slidenerd** [sahat/hackathon-starter#578]
First of all, thanks for your brilliant effort Sahat, this repo is the most comprehensive skeleton I have ever seen for a node.js express application. I have an issue where the connection on Mongoose seems to timeout, this is what the console says

```
✓ Express server listening on port 3000 in development mode.
✓ MongoDB connection established!
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
POST /api/messages 202 51.147 ms - -
./firstRun - waterfall() step 0 of 1
whats this 1
./firstRun - session.send()
load called again
./firstRun - session.sendBatch() sending 1 messages
✗ MongoDB connection error. Please make sure MongoDB is running. [Error: connection timeout]
```
The timeout happens after say 5-10 mins, any suggestions? Thanks for your response in advance

**Comment by sahat** [comment]
Hi @slidenerd, thanks for your kind words. This is the first I hear about this timeout issue with MongoDB in either development or production. If anyone has experienced a similar issue, please chime in.

**Comment by niallobrien** [comment]
@slidenerd Can you please provide some more details with regards to your system and Mongo setup? For example, I don't experience any timeout issues running Mongo on OSX or Windows.

**Comment by slidenerd** [comment]
I have this issue , I am sorry for the ugly looking log, let me know if you want me to paste it in a better place
```
**************************************************FIRST TIME**************************************************

? MongoDB connection error. Please make sure MongoDB is running. [Error: connection timeout]
session.sendBatch() sending 1 messages
POST /api/messages 202 36051.395 ms - -
MongoError: connection 2 to zupbot.documents.azure.com:10250 timed out
    at Function.MongoError.create (d:\nodejsapps\zup\0.0.2\node_modules\connect-mongo\node_modules\mongodb\node_modules\mongodb-core\lib\error.js:29:11)
    at TLSSocket.timeoutHandler (d:\nodejsapps\zup\0.0.2\node_modules\connect-mongo\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:173:20)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket.Socket._onTimeout (net.js:332:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
From previous event:
    at d:\nodejsapps\zup\0.0.2\node_modules\connect-mongo\src\index.js:248:48
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at MongoStore.set (d:\nodejsapps\zup\0.0.2\node_modules\connect-mongo\src\index.js:248:18)
    at Session.save (d:\nodejsapps\zup\0.0.2\node_modules\express-session\session\session.js:72:25)
    at Session.save (d:\nodejsapps\zup\0.0.2\node_modules\express-session\index.js:372:15)
    at ServerResponse.end (d:\nodejsapps\zup\0.0.2\node_modules\express-session\index.js:330:21)
    at ChatConnector.dispatch (d:\nodejsapps\zup\0.0.2\core\lib\bots\ChatConnector.js:353:13)
    at d:\nodejsapps\zup\0.0.2\core\lib\bots\ChatConnector.js:93:27
    at OpenIdMetadata.getKey (d:\nodejsapps\zup\0.0.2\core\lib\bots\OpenIdMetadata.js:25:13)
    at ChatConnector.verifyBotFramework (d:\nodejsapps\zup\0.0.2\core\lib\bots\ChatConnector.js:82:28)
    at ChatConnector.listen (d:\nodejsapps\zup\0.0.2\core\lib\bots\ChatConnector.js:36:23)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:91:12)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at serveStatic (d:\nodejsapps\zup\0.0.2\node_modules\express\node_modules\serve-static\index.js:75:16)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at d:\nodejsapps\zup\0.0.2\server.js:125:3
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at d:\nodejsapps\zup\0.0.2\server.js:114:3
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at xssProtection (d:\nodejsapps\zup\0.0.2\node_modules\lusca\lib\xssprotection.js:16:9)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at xframe (d:\nodejsapps\zup\0.0.2\node_modules\lusca\lib\xframes.js:12:9)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at d:\nodejsapps\zup\0.0.2\server.js:105:5
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at d:\nodejsapps\zup\0.0.2\node_modules\express-flash\lib\express-flash.js:31:7
    at module.exports (d:\nodejsapps\zup\0.0.2\node_modules\express-flash\node_modules\connect-flash\lib\flash.js:21:5)
    at module.exports (d:\nodejsapps\zup\0.0.2\node_modules\express-flash\lib\express-flash.js:22:5)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at SessionStrategy.module.exports.strategy.pass (d:\nodejsapps\zup\0.0.2\node_modules\passport\lib\middleware\authenticate.js:325:9)
    at SessionStrategy.authenticate (d:\nodejsapps\zup\0.0.2\node_modules\passport\lib\strategies\session.js:71:10)

"Error: connection timeout\n    at null.<anonymous> (d:\nodejsapps\zup\0.0.2\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:168:17)\n    at emitTwo (events.js:87:13)\n    at emit (events.js:172:7)\n    at listener (d:\nodejsapps\zup\0.0.2\node_modules\mongoose\node_modules\mongodb\lib\db.js:1791:14)\n    at emitOne (events.js:77:13)\n    at emit (events.js:169:7)\n    at Server.connect.errorHandler (d:\nodejsapps\zup\0.0.2\node_modules\mongoose\node_modules\mongodb\lib\server.js:270:14)\n    at g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at emit (events.js:169:7)\n    at eventHandler (d:\nodejsapps\zup\0.0.2\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:322:12)\n    at emitOne (events.js:77:13)\n    at emit (events.js:169:7)\n    at null.<anonymous> (d:\nodejsapps\zup\0.0.2\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:260:12)\n    at g (events.js:260:16)\n    at emitTwo (events.js:87:13)\n    at emit (events.js:172:7)\n    at TLSSocket.timeoutHandler (d:\nodejsapps\zup\0.0.2\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:172:10)\n    at TLSSocket.g (events.js:260:16)\n    at emitNone (events.js:67:13)\n    at TLSSocket.emit (events.js:166:7)\n    at TLSSocket.Socket._onTimeout (net.js:332:8)\n    at _runOnTimeout (timers.js:524:11)\n    at _makeTimerTimeout (timers.js:515:3)\n    at Timer.unrefTimeout (timers.js:584:5)"

**************************************************SECOND TIME**************************************************
MongoError: connection 1 to zupbot.documents.azure.com:10250 timed out
    at Function.MongoError.create (d:\nodejsapps\zup\0.0.2\node_modules\connect-mongo\node_modules\mongodb\node_modules\mongodb-core\lib\error.js:29:11)
    at TLSSocket.timeoutHandler (d:\nodejsapps\zup\0.0.2\node_modules\connect-mongo\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:173:20)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket.Socket._onTimeout (net.js:332:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
From previous event:
    at d:\nodejsapps\zup\0.0.2\node_modules\connect-mongo\src\index.js:248:48
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at MongoStore.set (d:\nodejsapps\zup\0.0.2\node_modules\connect-mongo\src\index.js:248:18)
    at Session.save (d:\nodejsapps\zup\0.0.2\node_modules\express-session\session\session.js:72:25)
    at Session.save (d:\nodejsapps\zup\0.0.2\node_modules\express-session\index.js:372:15)
    at ServerResponse.end (d:\nodejsapps\zup\0.0.2\node_modules\express-session\index.js:330:21)
    at ChatConnector.dispatch (d:\nodejsapps\zup\0.0.2\core\lib\bots\ChatConnector.js:353:13)
    at d:\nodejsapps\zup\0.0.2\core\lib\bots\ChatConnector.js:93:27
    at OpenIdMetadata.getKey (d:\nodejsapps\zup\0.0.2\core\lib\bots\OpenIdMetadata.js:25:13)
    at ChatConnector.verifyBotFramework (d:\nodejsapps\zup\0.0.2\core\lib\bots\ChatConnector.js:82:28)
    at ChatConnector.listen (d:\nodejsapps\zup\0.0.2\core\lib\bots\ChatConnector.js:36:23)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:91:12)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at serveStatic (d:\nodejsapps\zup\0.0.2\node_modules\express\node_modules\serve-static\index.js:75:16)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at d:\nodejsapps\zup\0.0.2\server.js:137:5
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at d:\nodejsapps\zup\0.0.2\server.js:126:5
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at xssProtection (d:\nodejsapps\zup\0.0.2\node_modules\lusca\lib\xssprotection.js:16:9)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at xframe (d:\nodejsapps\zup\0.0.2\node_modules\lusca\lib\xframes.js:12:9)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at d:\nodejsapps\zup\0.0.2\server.js:117:7
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at d:\nodejsapps\zup\0.0.2\node_modules\express-flash\lib\express-flash.js:31:7
    at module.exports (d:\nodejsapps\zup\0.0.2\node_modules\express-flash\node_modules\connect-flash\lib\flash.js:21:5)
    at module.exports (d:\nodejsapps\zup\0.0.2\node_modules\express-flash\lib\express-flash.js:22:5)
    at Layer.handle [as handle_request] (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:312:13)
    at d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:330:12)
    at next (d:\nodejsapps\zup\0.0.2\node_modules\express\lib\router\index.js:271:10)
    at SessionStrategy.module.exports.strategy.pass (d:\nodejsapps\zup\0.0.2\node_modules\passport\lib\middleware\authenticate.js:325:9)
    at SessionStrategy.authenticate (d:\nodejsapps\zup\0.0.2\node_modules\passport\lib\strategies\session.js:71:10)
```

**Comment by slidenerd** [comment]
This is what I have for connecting to Mongo
```
function connectToMongo() {
  const options = {
    server: { socketOptions: { keepAlive: 300000, connectTimeoutMS: 30000 } },
    replset: { socketOptions: { keepAlive: 300000, connectTimeoutMS: 30000 } }
  };
  mongoose.connect(process.env.MONGODB_URI || process.env.MONGOLAB_URI, options);
  mongoose.connection.on('connected', () => {
    console.log('%s MongoDB connection established!', chalk.green('✓'));
  });
  mongoose.connection.on('error', (error) => {
    console.log('%s MongoDB connection error. Please make sure MongoDB is running.', chalk.red('✗'), error);
  });
  // If the Node process ends, close the Mongoose connection
  process.on('SIGINT', exitDatabase).on('SIGTERM', exitDatabase);
}
```

Notice that in addition to code you guys had, I have added a SIGINT, SIGTERM event to handle a process exiting properly

**Comment by niallobrien** [comment]
That's very strange @slidenerd - is this happening locally?

**Comment by slidenerd** [comment]
Yes it is happening locally, I am not sure how to detect this on my Azure server though, so far my server code is running on alpha and has a few users and I havent seen this happening, I have just now removed the timeout options from the connection, will check if I get the error like before

**Comment by niallobrien** [comment]
Okay, can you give us some description of your local system and Mongo setup please?

**Comment by slidenerd** [comment]
Mongo shell version 3.2.9
This is what package.json looks like
```
{
  "name": "zup",
  "version": "0.0.2",
  "repository": {
    "type": "git",
    "url": "https://github.com/slidenerd/zupbot0.0.2"
  },
  "scripts": {
    "start": "node server.js",
    "test": "mocha --reporter spec --timeout 5000"
  },
  "dependencies": {
    "JSONStream": "^1.2.1",
    "async": "^2.0.1",
    "base64url": "^2.0.0",
    "bcrypt-nodejs": "^0.0.3",
    "body-parser": "^1.15.2",
    "chalk": "^1.1.3",
    "cheerio": "^0.22.0",
    "chrono-node": "^1.2.4",
    "clockwork": "^0.1.4",
    "compression": "^1.6.2",
    "connect-mongo": "^1.3.2",
    "dotenv": "^2.0.0",
    "errorhandler": "^1.4.3",
    "event-stream": "^3.3.4",
    "express": "^4.14.0",
    "express-flash": "^0.0.2",
    "express-session": "^1.14.1",
    "express-validator": "^2.20.8",
    "fbgraph": "^1.3.0",
    "github": "^3.1.0",
    "instagram-node": "^0.5.8",
    "jsonfile": "^2.4.0",
    "jsonwebtoken": "^7.1.9",
    "lastfm": "^0.9.2",
    "lob": "^3.9.0",
    "lodash": "^4.15.0",
    "lusca": "^1.4.1",
    "memory-cache": "^0.1.6",
    "mongoose": "^4.6.0",
    "morgan": "^1.7.0",
    "multer": "^1.2.0",
    "node-foursquare": "^0.3.0",
    "node-geocoder": "^3.15.0",
    "node-linkedin": "^0.5.4",
    "node-sass-middleware": "^0.9.8",
    "nodemailer": "^2.6.0",
    "nodemon": "^1.10.2",
    "passport": "0.3.2",
    "passport-facebook": "^2.1.1",
    "passport-github": "^1.1.0",
    "passport-google-oauth": "^1.0.0",
    "passport-instagram": "^1.0.0",
    "passport-linkedin-oauth2": "^1.4.1",
    "passport-local": "^1.0.0",
    "passport-oauth": "^1.0.0",
    "passport-openid": "^0.4.0",
    "passport-twitter": "^1.0.4",
    "paypal-rest-sdk": "^1.6.9",
    "pug": "^2.0.0-beta6",
    "request": "^2.74.0",
    "rivescript": "^1.16.0",
    "rsa-pem-from-mod-exp": "^0.8.4",
    "sprintf-js": "^1.0.3",
    "stripe": "^4.11.0",
    "tumblr.js": "^1.1.1",
    "twilio": "^3.3.1-edge",
    "twit": "^2.2.4",
    "uuid": "^2.0.3",
    "validator": "^6.0.0"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "mocha": "^3.0.2",
    "supertest": "^2.0.0"
  },
  "engines": {
    "node": "6.7.0"
  },
  "license": "MIT"
}
```
That would be my Windows machine config
![capture](https://cloud.githubusercontent.com/assets/5139030/19114239/bd835378-8b2a-11e6-8e0b-a4c701d42842.PNG)

node --version says 4.5.0

Let me know what other information I can provide
Thank you for your time

**Comment by niallobrien** [comment]
I'm no expert, but have tried this on Windows with no issues. However, I'm running node 6.6.0.
Do you have NVM installed within Windows?

**Comment by slidenerd** [comment]
No I am not using NVM on Windows but I can uninstall node and put it back through NVM if you want for the latest version

**Comment by niallobrien** [comment]
I think testing with the latest version of node would certainly help reduce the number of possible variables at play here. I'm sorry I can't be of any more help.

**Comment by slidenerd** [comment]
you have already helped more than anyone else has 👍 I will do a node update and let you know if there are any issues, if not i ll come and close this one

**Comment by niallobrien** [comment]
Please do keep us posted, this is a great project and I'm glad to see more & more people use it. :+1:

**Comment by slidenerd** [comment]
This is not a great project lol, this is the BEST project I have seen, currently I am quite occupied but when I am free I would love to have you guys on my YouTube channel and talk about this project, I have a 110k subs on YouTube who are pure programmers and would love to see this. Channel is 'slidenerd' if you look it up. If interested, let me know

**Comment by niallobrien** [comment]
@sahat Perfect invitation right there! ^
@slidenerd Awesome stuff - I'll be sure to check it out, I love geeking out!

**Comment by slidenerd** [comment]
I look forward to seeing you guys on my channel, we can do a G+ hangout or Skype depending on your choice. Currently a bit busy deploying this project but we can do this is say 10-15 days, feel free to reach me via email at s_l&i#d/e*n@e^r_d@gmail.com

**Comment by slidenerd** [comment]
The latest version of node.js has fixed the issue. Thank you for all your assistance and let me know if you guys are available on a weekend for a chat. Would like to make a video telling about your project. Regards
