### ISSUE TITLE
Connect-mongo issue

### ISSUE THREAD

**Issue by kaneschutzman** [sahat/hackathon-starter#634]
No matter which version of node I use and other various version downgrades with mongoose/connect-mongo I still get the same issue.  I'm connecting to Mongolab which only supports Mongodb 3.2 now.  

MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/home/ubuntu/workspace/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/home/ubuntu/workspace/node_modules/mongodb-core/lib/connection/pool.js:272:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/ubuntu/workspace/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by kaneschutzman** [comment]
Well maybe it was me but using Mongodb V3.4 locally works just fine.

**Comment by robbiegleeson** [comment]
Have you been able to identify the issue?

**Comment by adhorrig** [comment]
I got the same issue.

Problem was that I never set a path to save the database: ```mongod --dbpath <path to data directory>```

Then used sudo to start the service: ```sudo mongod```

See (here)[https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/] and (here)[http://stackoverflow.com/questions/41420466/mongodb-shuts-down-with-code-100]

**Comment by trafflux** [comment]
OP's issue is likely that he didn't edit the .env file to specify the url to his mlab database. It was still looking for a mongodb install on the localhost.

**Comment by JackEdwardLyons** [comment]
I'm having similar issues. I followed along the comments above and mongo is running but I still get an error. Thanks for the help in advance; here is the output:

```
node:96303) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
✓ App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop


/Users/jlyons/Documents/Code/Fullstack/test-project/node_modules/mongodb/lib/mongo_client.js:415
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOTFOUND localhost localhost:27017]
    at Pool.<anonymous> (/Users/jlyons/Documents/Code/Fullstack/test-project/node_modules/mongodb-core/lib/topologies/server.js:329:35)
    at Pool.emit (events.js:159:13)
    at Connection.<anonymous> (/Users/jlyons/Documents/Code/Fullstack/test-project/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:254:19)
    at Connection.emit (events.js:159:13)
    at Socket.<anonymous> (/Users/jlyons/Documents/Code/Fullstack/test-project/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

And Mongo is open and running here:
```
[initandlisten] MongoDB starting : pid=96291 port=27017 dbpath=/data/db 64-bit host=jack-lyons-macbook-pro.local
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten] db version v3.6.0
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten] git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten] allocator: system
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten] modules: none
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten] build environment:
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten]     distarch: x86_64
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-01-15T19:00:41.622+1000 I CONTROL  [initandlisten] options: {}
2018-01-15T19:00:41.623+1000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-01-15T19:00:41.623+1000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-01-15T19:00:41.952+1000 I STORAGE  [initandlisten] WiredTiger message [1516006841:952707][96291:0x7fffd778f3c0], txn-recover: Main recovery loop: starting at 7/6400
2018-01-15T19:00:42.072+1000 I STORAGE  [initandlisten] WiredTiger message [1516006842:72137][96291:0x7fffd778f3c0], txn-recover: Recovering log 7 through 8
2018-01-15T19:00:42.160+1000 I STORAGE  [initandlisten] WiredTiger message [1516006842:160330][96291:0x7fffd778f3c0], txn-recover: Recovering log 8 through 8
2018-01-15T19:00:42.372+1000 I CONTROL  [initandlisten]
2018-01-15T19:00:42.372+1000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-01-15T19:00:42.372+1000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-01-15T19:00:42.372+1000 I CONTROL  [initandlisten]
2018-01-15T19:00:42.372+1000 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-01-15T19:00:42.372+1000 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server.
2018-01-15T19:00:42.373+1000 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP
2018-01-15T19:00:42.373+1000 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-01-15T19:00:42.373+1000 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-01-15T19:00:42.373+1000 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-01-15T19:00:42.373+1000 I CONTROL  [initandlisten]
2018-01-15T19:00:42.386+1000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-01-15T19:00:42.386+1000 I NETWORK  [initandlisten] waiting for connections on port 27017
```
