### ISSUE TITLE
Error on running mocha tests

### ISSUE THREAD

**Issue by gs-rbarman** [sahat/hackathon-starter#679]
**Error looks like as mentioned below**

Uncaught error outside test suite:
Uncaught Error: listen EADDRINUSE :::3000
      at Object.exports._errnoException (util.js:1023:11)
      at exports._exceptionWithHostPort (util.js:1046:20)
      at Server._listen2 (net.js:1261:14)
      at listen (net.js:1297:10)
      at Server.listen (net.js:1375:9)
      at Function.listen (node_modules/express/lib/application.js:618:24)
      at Object.<anonymous> (app.js:227:5)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (test/app.js:2:13)
      at require (internal/module.js:20:19)
      at Array.forEach (native)
      at run (bootstrap_node.js:418:7)
      at startup (bootstrap_node.js:139:9)
      at bootstrap_node.js:533:3

**Comment by YasharF** [comment]
Is this still an issue, or are you unblocked now?
