### ISSUE TITLE
cannot get mongodb to work

### ISSUE THREAD

**Issue by TinHint** [sahat/hackathon-starter#681]
I am using MongoDB Atalas
After install the project, I changed the config in the .env file, replacing the default mongodb://localhost:27017/test with below. (password and database value applied). But I am getting below error when starting the app.js

MONGODB_URI=mongodb://yalaadmin:<PASSWORD>@cluster0-shard-00-00-nxsdd.mongodb.net:27017,cluster0-shard-00-01-nxsdd.mongodb.net:27017,cluster0-shard-00-02-nxsdd.mongodb.net:27017/<DATABASE>?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin
MONGODB_URI=mongodb://yalaadmin:<PASSWORD>@cluster0-shard-00-00-nxsdd.mongodb.net:27017,cluster0-shard-00-01-nxsdd.mongodb.net:27017,cluster0-shard-00-02-nxsdd.mongodb.net:27017/<DATABASE>?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin

✓ App is running at http://localhost:3000 in development mode
  Press CTRL-C to stop

/home/ec2-user/app/hackathon-starter-master/node_modules/mongodb/lib/mongo_client.js:338
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/ec2-user/app/hackathon-starter-master/node_modules/mongodb-core/lib/topologies/server.js:327:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:191:7)
    at Connection.<anonymous> (/home/ec2-user/app/hackathon-starter-master/node_modules/mongodb-core/lib/connection/pool.js:274:12)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at Socket.<anonymous> (/home/ec2-user/app/hackathon-starter-master/node_modules/mongodb-core/lib/connection/connection.js:177:49)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Seems like the config I made in the .env file is not getting used, anyone could help me out? Many thanks in advance.

**Comment by kuriakinzeng** [comment]
I encountered the same issue, and get passed that error by removing .env.example

**Comment by kuriakinzeng** [comment]
Have you changed ```dotenv.load({ path: '.env.example' });``` to ```dotenv.load({ path: '.env' });``` in your app.js?

**Comment by TinHint** [comment]
I have got it working now. thanks a lot for the help

**Comment by kuriakinzeng** [comment]
Awesome! You're welcome.
