### ISSUE TITLE
 SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by cbll** [sahat/hackathon-starter#688]
I followed the "getting started" points, however, running `node app.js` results in the following: 

 compile: [(...args) => this._convertDataImages(...args)],
                       ^^^

```
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/hackathon/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/hackathon/controllers/user.js:3:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

Never used Node before so not sure where to begin. Maybe it's the global dependencies on my system messing with it?

**Comment by cbll** [comment]
Had to update my global dependency of node. Fixed by this: https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

**Comment by acesssantu** [comment]
I came across this issue, while configuring the Protractor, trying to update/start selenium webdriver manager, 

webdriver-manger update
webdriver-manager start

Results in Error message :
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\<XXXXXXXX>\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\cli\index.js:9:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Fix: Reinstall node with the latest version and it works fine.
Thanks! cbII
