### ISSUE TITLE
User validation fails

### ISSUE THREAD

**Issue by gkatsanos** [sahat/hackathon-starter#731]
Hey @sahat , very good job and thank you for making this.
I am using a "modified version" of your starter boilerplate , but copied the Facebook strategy as-is : 

```javascript

passport.use(new FacebookStrategy({
  clientID: 8429769831,
  clientSecret: '********************',
  callbackURL: '/auth/facebook/callback',
  profileFields: ['name', 'email', 'link', 'locale', 'timezone', 'gender'],
  passReqToCallback: true,
}, (req, accessToken, refreshToken, profile, done) => {
  if (req.user) {
    User.findOne({ facebook: profile.id }, (err, existingUser) => {
      if (err) { return done(err); }
      if (existingUser) {
        req.flash('errors', { msg: 'There is already a Facebook account that belongs to you. Sign in with that account or delete it, then link it with your current account.' });
        done(err);
      } else {
        User.findById(req.user.id, (err, user) => {
          if (err) { return done(err); }
          user.facebook = profile.id;
          user.tokens.push({ kind: 'facebook', accessToken });
          user.lastName = user.lastName || `${profile.name.familyName}`;
          user.gender = user.gender || profile.gender;
          user.picture = user.picture || `https://graph.facebook.com/${profile.id}/picture?type=large`;
          user.save((err) => {
            req.flash('info', { msg: 'Facebook account has been linked.' });
            done(err, user);
          });
        });
      }
    });
  } else {
    User.findOne({ facebook: profile.id }, (err, existingUser) => {
      if (err) { return done(err); }
      if (existingUser) {
        return done(null, existingUser);
      }
      User.findOne({ username: profile._json.email }, (err, existingEmailUser) => {
        if (err) { return done(err); }
        if (existingEmailUser) {
          req.flash('errors', { msg: 'There is already an account using this email address. Sign in to that account and link it with Facebook manually from Account Settings.' });
          done(err);
        } else {
          const user = new User();
          user.username = profile._json.email;
          user.facebook = profile.id;
          user.tokens.push({ kind: 'facebook', accessToken });
          user.lastName = `${profile.name.familyName}`;
          user.firstName = `${profile.name.givenName}`;
          user.gender = profile._json.gender;
          user.picture = `https://graph.facebook.com/${profile.id}/picture?type=large`;
          user.location = (profile._json.location) ? profile._json.location.name : '';
          user.save((err) => {
            done(err, user);
          });
        }
      });
    });
  }
}));
```

I have changed some fields to correspond to my model:

```javascript
const userSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    lowercase: true,
  },
  facebook: String,
  password: {
    type: String,
    required: true,
    minlength: 4,
    maxlength: 128,
  },
  firstName: {
    type: String,
    maxlength: 128,
    trim: true,
  },
  lastName: {
    type: String,
    maxlength: 128,
    trim: true,
  },
  gender: {
    type: Number,
    min: 1,
    max: 3,
  },
  picture: String,
  location: String,
  tokens: Array,
}, {
  timestamps: true,
});
```

When I try to login via facebook I get:

```
ValidationError: User validation failed
    at ValidationError (/Users/gplus/vm/isawyou/server/node_modules/mongoose/lib/error/validation.js:28:11)
    at model.Document.invalidate (/Users/gplus/vm/isawyou/server/node_modules/mongoose/lib/document.js:1612:32)
    at model.Document.set (/Users/gplus/vm/isawyou/server/node_modules/mongoose/lib/document.js:761:10)
    at model.set [as gender] (/Users/gplus/vm/isawyou/server/node_modules/mongoose/lib/document.js:1982:25)
    at User.findOne.User.findOne (/Users/gplus/vm/isawyou/server/src/config/passport.js:64:23)
    at model.Query.<anonymous> (/Users/gplus/vm/isawyou/server/node_modules/mongoose/lib/model.js:3832:16)
    at /Users/gplus/vm/isawyou/server/node_modules/kareem/index.js:273:21
    at /Users/gplus/vm/isawyou/server/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Here are my routes: (they're in a separate auth.routes.js file) 

```javascript
router.route('/facebook')
  .get(controller.auth);

router.route('/facebook/callback')
  .get(controller.auth, (req, res) => res.redirect(req.session.returnTo || '/'));
```

And my controller: 

```javascript
exports.auth = passport.authenticate('facebook', {
  scope: ['email', 'public_profile'],
});

exports.authCallback = passport.authenticate('facebook', {
  failureRedirect: '/login',
});

```

**Comment by gkatsanos** [comment]
My gender field didn't validate.
