### ISSUE TITLE
Error logging during password reset

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#732]
At line https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L265 if the `user.save` failes, it doesn't look like if it gets exposed that the specific user.save is the cause of the failur, is it?  Should that line get broken up so errors from user.save can get logged in that spot?  Let me know if I am missing something.

Same with https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L341

**Comment by niallobrien** [comment]
I would assume that the error would be passed into the promise chain and resolved when rejected, though I cannot be 100% certain. Perhaps kill your Mongo instance and trigger this function to test what happens, I'm curious to know too.

**Comment by YasharF** [comment]
Tried it and got a 500 error in the browser:

```
**Connect**
500 MongoError: failed to reconnect after 30 attempts with interval 1000 ms
   at Connection.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:318:15)
   at emitTwo (events.js:126:13)
   at Connection.emit (events.js:214:7)
   at Socket.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/connection.js:189:49)
   at Object.onceWrapper (events.js:315:30)
   at emitOne (events.js:116:13)
   at Socket.emit (events.js:211:7)
   at emitErrorNT (internal/streams/destroy.js:64:8)
   at _combinedTickCallback (internal/process/next_tick.js:138:11)
   at process._tickCallback (internal/process/next_tick.js:180:9)
```

And an error in the console:
```
MongoError: failed to reconnect after 30 attempts with interval 1000 ms
    at Connection.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:318:15)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
MongoError: failed to reconnect after 30 attempts with interval 1000 ms
    at Connection.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:318:15)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
MongoError: failed to reconnect after 30 attempts with interval 1000 ms
    at Connection.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:318:15)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
MongoError: failed to reconnect after 30 attempts with interval 1000 ms
    at Connection.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:318:15)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
MongoError: failed to reconnect after 30 attempts with interval 1000 ms
    at Connection.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:318:15)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
MongoError: failed to reconnect after 30 attempts with interval 1000 ms
    at Connection.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/pool.js:318:15)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/mnt/c/temp/hackathon-starter/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
POST /forgot 500 31365.644 ms - -
```

**Comment by niallobrien** [comment]
Wow, that's interesting. Once we move to async/await the code here will be much cleaner and we can catch errors much cleaner. Do you think we should implement a fix in the meantime?

**Comment by YasharF** [comment]
It might be duplicate effort, I looking to see if there are other places.

**Comment by YasharF** [comment]
It looks like that all errors in the user controller are handled that way.  But  in the contact controller, if there is an error with sendMail it will flash the error message: https://github.com/sahat/hackathon-starter/blob/master/controllers/contact.js#L46

I would opt for closing this ticket in favor of better/more error handling when moving to move to async/await
