### ISSUE TITLE
Cannot run on rPi, same issue on PC

### ISSUE THREAD

**Issue by berrytecnhnics** [sahat/hackathon-starter#734]
Im not very experienced with express or mongodb, but wanted to use this boilerplate to mess with live code.
I got a warning that sinon-mongoose@2.0.2 requires a peer of sinon@^2.1.0 but none was installed.
I was able to manually install the modules on my PC and get it to run, but on my rPi i get the following. I realize that this boilerplate is not stated to work on rPi but i cant figure out what is stopping it.
(rPi 2 for the record)
Here is my recurring error

`node app.js
/home/pi/Node/Template/node_modules/nodemailer/lib/mailer/index.js:31
            compile: [(...args) => this._convertDataImages(...args)],
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/pi/Node/Template/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/pi/Node/Template/controllers/user.js:3:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/pi/Node/Template/app.js:34:24)
`

**Comment by YasharF** [comment]
I have seen the peer warning on initial npm installs, but haven't to do anything about it to get the code to work as is.

For an error message like what you have I would suggest working it from the specific errors to see what is causing an issue.  For example, the last line that you posted is "at Object. (/home/pi/Node/Template/app.js:34:24)".  So what is at line 34, character 24 in app.js in your project?

**Comment by berrytecnhnics** [comment]
Ive tabled it for now and started a heroku account to test on, but ill definitely come back to it as i would like my finished product to run on a Pi.
