### ISSUE TITLE
last.fm API endpoint fails

### ISSUE THREAD

**Issue by cdupuis** [sahat/hackathon-starter#939]
Current master fails with the following error when running the tests:

```
  18 passing (12s)
  1 failing

  1) GET /api/lastfm
       should return 200 OK:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1600:8)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

Also a http GET against `api/lastfm` fails in the same way.

**Comment by YasharF** [comment]
Their endpoint is down: https://getsatisfaction.com/lastfm/topics/the-api-doesnt-seem-to-return-data-anymore

We probably need to handle the error better in this project as well.
