### ISSUE TITLE
node app.js fails

### ISSUE THREAD

**Issue by alexdevero** [sahat/hackathon-starter#940]
Running `node app.js` ends with an error.

Whole log:
```
$ npm install

> node-sass@4.11.0 install C:\hackathon-app\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\AppData\Roaming\npm-cache\node-sass\4.11.0\win32-x64-67_binding.node

> node-sass@4.11.0 postinstall C:\hackathon-app\node_modules\node-sass
> node scripts/build.js

Binary found at C:\hackathon-app\node_modules\node-sass\vendor\win32-x64-67\binding.node
Testing binary
Binary is fine

> hackathon-starter@5.1.2 postinstall C:\hackathon-app
> npm rebuild node-sass


> node-sass@4.11.0 install C:\hackathon-app\node_modules\node-sass
> node scripts/install.js

node-sass build Binary found at C:\hackathon-app\node_modules\node-sass\vendor\win32-x64-67\binding.node

> node-sass@4.11.0 postinstall C:\hackathon-app\node_modules\node-sass
> node scripts/build.js

Binary found at C:\hackathon-app\node_modules\node-sass\vendor\win32-x64-67\binding.node
Testing binary
Binary is fine
node-sass@4.11.0 C:\hackathon-app\node_modules\node-sass
npm WARN sinon-mongoose@2.2.1 requires a peer of sinon@5 - 6 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

added 1024 packages from 1402 contributors and audited 4278 packages in 157.75s
found 0 vulnerabilities

$ node app.js
✓ App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop


C:\hackathon-app\node_modules\mongodb\lib\mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\hackathon-app\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at Pool.emit (events.js:197:13)
    at Connection.<anonymous> (C:\hackathon-app\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:285:13)
    at Connection.emit (events.js:197:13)
    at Socket.<anonymous> (C:\hackathon-app\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:285:13)
    at Socket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

Node: 11.10.0
NPM: 6.8.0
OS: Win 10

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter#prerequisites

**Comment by alexdevero** [comment]
@YasharF MongoDB. My mistake. Thank you Yashar.
