### ISSUE TITLE
Bug: Login by email after creating an account using a provider

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#992]
Test case:
1. The user creates an account using Google.
2. The user goes to the profile page and changes their email address to a different email than their Google account's email address.
3. The user logs out
4. The user tries to login using the email address that they used in step 2.

The server crashes with the following error:
```
2019-07-28T18:50:04.974300+00:00 app[web.1]: GET /login 200 21.277 ms - -
2019-07-28T18:50:06.624552+00:00 app[web.1]: Error: data and hash arguments required
2019-07-28T18:50:06.624567+00:00 app[web.1]: at Object.compare (/app/node_modules/bcrypt/bcrypt.js:209:17)
2019-07-28T18:50:06.624570+00:00 app[web.1]: at model.comparePassword (/app/models/User.js:53:10)
2019-07-28T18:50:06.624572+00:00 app[web.1]: at /app/config/passport.js:39:10
2019-07-28T18:50:06.624574+00:00 app[web.1]: at /app/node_modules/mongoose/lib/model.js:4567:16
2019-07-28T18:50:06.624576+00:00 app[web.1]: at /app/node_modules/mongoose/lib/query.js:4314:12
2019-07-28T18:50:06.624579+00:00 app[web.1]: at /app/node_modules/mongoose/lib/query.js:2797:28
2019-07-28T18:50:06.624581+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:75:11)
2019-07-28T18:50:06.631624+00:00 app[web.1]: POST /login 500 15.197 ms - 12
```

The error does not occur if the user also sets a password in the profile page.

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/a9453342b3550c5bba325b131e2dfb401edb910b
